FROM debian:12-slim

ARG IMAGE_VERSION='v1.0.0-devel'
ARG MAINTAINER='https://github.com/jsknnr/vintage-story-server'

ARG CONTAINER_GID=10000
ARG CONTAINER_UID=10000

ARG SUPERCRONIC_BINARY="https://github.com/aptible/supercronic/releases/download/v0.2.33/supercronic-linux-amd64"
ARG DOTNET_RUNTIME='https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.19/aspnetcore-runtime-8.0.19-linux-x64.tar.gz'

ENV GAME_BRANCH='stable'
ENV GAME_VERSION='1.21.2'
ENV BACKUP_RETENTION_DAYS=7
ENV BACKUP_CRON_SCHEDULE='0 3 * * *'

ENV VINTAGE_STORY_PATH='/home/vintagestory'
ENV DOTNET_PATH='/.dotnet'

RUN groupadd -g $CONTAINER_GID vintagestory \
    && useradd -g $CONTAINER_GID -u $CONTAINER_UID -m vintagestory \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        ca-certificates \
        wget \
        libicu72 \
        supervisor \
        jq \
        lsof \
        vim \
    && wget "$DOTNET_RUNTIME" \
    && mkdir "$DOTNET_PATH" \
    && tar xzf aspnetcore-runtime-8.0.19-linux-x64.tar.gz -C "$DOTNET_PATH" \
    && rm -f aspnetcore-runtime-8.0.19-linux-x64.tar.gz \
    && wget "$SUPERCRONIC_BINARY" \
    && chmod +x supercronic-linux-amd64 \
    && mv supercronic-linux-amd64 /usr/local/bin/supercronic \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && apt-get autoremove -y

USER vintagestory

RUN mkdir -p "${VINTAGE_STORY_PATH}/server" \
    && mkdir -p "${VINTAGE_STORY_PATH}/data" \
    && echo "${IMAGE_VERSION}" > "${VINTAGE_STORY_PATH}/image_version" \
    && echo "${MAINTAINER}" > "${VINTAGE_STORY_PATH}/image_maintainer" \
    && echo "${CONTAINER_UID}:${CONTAINER_GID}" > "${VINTAGE_STORY_PATH}/expected_filesystem_permissions"

COPY entrypoint.sh "${VINTAGE_STORY_PATH}/entrypoint.sh"
COPY backup.sh "${VINTAGE_STORY_PATH}/backup.sh"
COPY build_serverconfig.sh "${VINTAGE_STORY_PATH}/build_serverconfig.sh"
COPY supervisord.conf "${VINTAGE_STORY_PATH}/supervisord.conf"
COPY example_serverconfig.json "${VINTAGE_STORY_PATH}/example_serverconfig.json"

WORKDIR "$VINTAGE_STORY_PATH"

CMD ["./entrypoint.sh"]
