apiVersion: v1
kind: ConfigMap
metadata:
  name: serverconfig
data:
  serverconfig.json: |
    {
      "FileEditWarning": "",
      "ConfigVersion": "1.5",
      "ServerName": {{ .Values.serverConfig.serverName | quote }},
      "ServerUrl": null,
      "ServerDescription": {{ if .Values.serverConfig.serverDescription }}{{ .Values.serverConfig.serverDescription | quote }}{{ else }}null{{ end }},
      "WelcomeMessage": {{ .Values.serverConfig.welcomeMessage | quote }},
      "Ip": null,
      "Port": {{ .Values.config.gamePort | int }},
      "Upnp": false,
      "CompressPackets": true,
      "AdvertiseServer": {{ .Values.serverConfig.advertiseServer }},
      "MaxClients": {{ .Values.serverConfig.maxPlayers | int }},
      "PassTimeWhenEmpty": false,
      "MasterserverUrl": "http://masterserver.vintagestory.at/api/v1/servers/",
      "ModDbUrl": "https://mods.vintagestory.at/",
      "ClientConnectionTimeout": 150,
      "EntityDebugMode": false,
      "Password": {{ if .Values.serverConfig.password }}{{ .Values.serverConfig.password | quote }}{{ else }}null{{ end }},
      "MapSizeX": {{ .Values.serverConfig.mapSizeX | int }},
      "MapSizeY": {{ .Values.serverConfig.mapSizeY | int }},
      "MapSizeZ": {{ .Values.serverConfig.mapSizeZ | int }},
      "ServerLanguage": {{ .Values.serverConfig.serverLanguage | quote }},
      "MaxChunkRadius": 12,
      "TickTime": 33.333332,
      "SpawnCapPlayerScaling": 0.5,
      "BlockTickChunkRange": 4,
      "MaxMainThreadBlockTicks": 10000,
      "RandomBlockTicksPerChunk": 16,
      "BlockTickInterval": 300,
      "SkipEveryChunkRow": 0,
      "SkipEveryChunkRowWidth": 0,
      "Roles": [
        {
          "Code": "suvisitor",
          "PrivilegeLevel": -1,
          "Name": "Survival Visitor",
          "Description": "Can only visit this world and chat but not use/place/break anything",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "chat"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 1,
          "Color": "Green",
          "LandClaimAllowance": 0,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 3,
          "AutoGrant": false
        },
        {
          "Code": "crvisitor",
          "PrivilegeLevel": -1,
          "Name": "Creative Visitor",
          "Description": "Can only visit this world, chat and fly but not use/place/break anything",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "chat"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 2,
          "Color": "DarkGray",
          "LandClaimAllowance": 0,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 3,
          "AutoGrant": false
        },
        {
          "Code": "limitedsuplayer",
          "PrivilegeLevel": -1,
          "Name": "Limited Survival Player",
          "Description": "Can use/place/break blocks only in permitted areas (priv level -1), create/manage player groups and chat",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "controlplayergroups",
            "manageplayergroups",
            "chat",
            "build",
            "useblock",
            "attackcreatures",
            "attackplayers",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 1,
          "Color": "White",
          "LandClaimAllowance": 0,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 3,
          "AutoGrant": false
        },
        {
          "Code": "limitedcrplayer",
          "PrivilegeLevel": -1,
          "Name": "Limited Creative Player",
          "Description": "Can use/place/break blocks in only in permitted areas (priv level -1), create/manage player groups, chat, fly and set his own game mode (= allows fly and change of move speed)",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "controlplayergroups",
            "manageplayergroups",
            "chat",
            "build",
            "useblock",
            "gamemode",
            "freemove",
            "attackcreatures",
            "attackplayers",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 2,
          "Color": "LightGreen",
          "LandClaimAllowance": 0,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 3,
          "AutoGrant": false
        },
        {
          "Code": "suplayer",
          "PrivilegeLevel": 0,
          "Name": "Survival Player",
          "Description": "Can use/place/break blocks in unprotected areas (priv level 0), create/manage player groups and chat. Can claim an area of up to 8 chunks.",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "controlplayergroups",
            "manageplayergroups",
            "chat",
            "areamodify",
            "build",
            "useblock",
            "attackcreatures",
            "attackplayers",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 1,
          "Color": "White",
          "LandClaimAllowance": 262144,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 3,
          "AutoGrant": false
        },
        {
          "Code": "crplayer",
          "PrivilegeLevel": 100,
          "Name": "Creative Player",
          "Description": "Can use/place/break blocks in all areas (priv level 100), create/manage player groups, chat, fly and set his own game mode (= allows fly and change of move speed). Can claim an area of up to 40 chunks.",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "controlplayergroups",
            "manageplayergroups",
            "chat",
            "areamodify",
            "build",
            "useblock",
            "gamemode",
            "freemove",
            "attackcreatures",
            "attackplayers",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 2,
          "Color": "LightGreen",
          "LandClaimAllowance": 1310720,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 6,
          "AutoGrant": false
        },
        {
          "Code": "sumod",
          "PrivilegeLevel": 200,
          "Name": "Survival Moderator",
          "Description": "Can use/place/break blocks everywhere (priv level 200), create/manage player groups, chat, kick/ban players and do serverwide announcements. Can claim an area of up to 4 chunks.",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "controlplayergroups",
            "manageplayergroups",
            "chat",
            "areamodify",
            "build",
            "useblock",
            "buildblockseverywhere",
            "useblockseverywhere",
            "kick",
            "ban",
            "announce",
            "readlists",
            "attackcreatures",
            "attackplayers",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 1,
          "Color": "Cyan",
          "LandClaimAllowance": 1310720,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 60,
          "AutoGrant": false
        },
        {
          "Code": "crmod",
          "PrivilegeLevel": 500,
          "Name": "Creative Moderator",
          "Description": "Can use/place/break blocks everywhere (priv level 500), create/manage player groups, chat, kick/ban players, fly and set his own or other players game modes (= allows fly and change of move speed). Can claim an area of up to 40 chunks.",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "controlplayergroups",
            "manageplayergroups",
            "chat",
            "areamodify",
            "build",
            "useblock",
            "buildblockseverywhere",
            "useblockseverywhere",
            "kick",
            "ban",
            "gamemode",
            "freemove",
            "commandplayer",
            "announce",
            "readlists",
            "attackcreatures",
            "attackplayers",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 2,
          "Color": "Cyan",
          "LandClaimAllowance": 1310720,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 60,
          "AutoGrant": false
        },
        {
          "Code": "admin",
          "PrivilegeLevel": 99999,
          "Name": "Admin",
          "Description": "Has all privileges, including giving other players admin status.",
          "DefaultSpawn": null,
          "ForcedSpawn": null,
          "Privileges": [
            "build",
            "useblock",
            "buildblockseverywhere",
            "useblockseverywhere",
            "attackplayers",
            "attackcreatures",
            "freemove",
            "gamemode",
            "pickingrange",
            "chat",
            "kick",
            "ban",
            "whitelist",
            "setwelcome",
            "announce",
            "readlists",
            "give",
            "areamodify",
            "setspawn",
            "controlserver",
            "tp",
            "time",
            "grantrevoke",
            "root",
            "commandplayer",
            "controlplayergroups",
            "manageplayergroups",
            "selfkill"
          ],
          "RuntimePrivileges": [],
          "DefaultGameMode": 1,
          "Color": "LightBlue",
          "LandClaimAllowance": 2147483647,
          "LandClaimMinSize": {
            "X": 5,
            "Y": 5,
            "Z": 5
          },
          "LandClaimMaxAreas": 99999,
          "AutoGrant": true
        }
      ],
      "DefaultRoleCode": "suplayer",
      "ModPaths": [
        "Mods",
        "/home/vintagestory/data/Mods"
      ],
      "AntiAbuse": 0,
      "WorldConfig": {
        "Seed": {{ if .Values.serverConfig.seed }}{{ .Values.serverConfig.seed | quote }}{{ else }}null{{ end }},
        "SaveFileLocation": "/home/vintagestory/data/Saves/default.vcdbs",
        "WorldName": {{ .Values.serverConfig.worldName | quote }},
        "AllowCreativeMode": {{ .Values.serverConfig.allowCreative }},
        "PlayStyle": {{ .Values.serverConfig.playStyle | quote }},
        "PlayStyleLangCode": {{ .Values.serverConfig.playStyleLangCode | quote }},
        "WorldType": "standard",
        "WorldConfiguration": {
          "gameMode": {{ .Values.serverConfig.gameMode | quote }},
          "startingClimate": {{ .Values.serverConfig.startingClimate | quote }},
          "spawnRadius": {{ .Values.serverConfig.spawnRadius | quote }},
          "graceTimer": {{ .Values.serverConfig.graceTimer | quote }},
          "deathPunishment": {{ .Values.serverConfig.deathPunishment | quote }},
          "droppedItemsTimer": {{ .Values.serverConfig.droppedItemsTimer | quote }},
          "seasons": {{ .Values.serverConfig.seasons | quote }},
          "playerlives": {{ .Values.serverConfig.playerLives | quote }},
          "lungCapacity": {{ .Values.serverConfig.lungCapacity | quote }},
          "daysPerMonth": {{ .Values.serverConfig.daysPerMonth | quote }},
          "harshWinters": {{ .Values.serverConfig.harshWinters | quote }},
          "blockGravity": {{ .Values.serverConfig.blockGravity | quote }},
          "caveIns": {{ .Values.serverConfig.caveIns | quote }},
          "allowUndergroundFarming": {{ .Values.serverConfig.allowUndergroundFarming }},
          "bodyTemperatureResistance": {{ .Values.serverConfig.bodyTemperatureResistance | quote }},
          "creatureHostility": {{ .Values.serverConfig.creatureHostility | quote }},
          "creatureStrength": {{ .Values.serverConfig.creatureStrength | quote }},
          "playerHealthPoints": {{ .Values.serverConfig.playerHealthPoints | quote }},
          "playerHungerSpeed": {{ .Values.serverConfig.playerHungerSpeed | quote }},
          "playerHealthRegenSpeed": {{ .Values.serverConfig.playerHealthRegenSpeed | quote }},
          "playerMoveSpeed": {{ .Values.serverConfig.playerMoveSpeed | quote }},
          "foodSpoilSpeed": {{ .Values.serverConfig.foodSpoilSpeed | quote }},
          "saplingGrowthRate": {{ .Values.serverConfig.saplingGrowthRate | quote }},
          "toolDurability": {{ .Values.serverConfig.toolDurability | quote }},
          "toolMiningSpeed": {{ .Values.serverConfig.toolMiningSpeed | quote }},
          "propickNodeSearchRadius": {{ .Values.serverConfig.propickNodeSearchRadius | quote }},
          "globalDepositSpawnRate": {{ .Values.serverConfig.globalDepositSpawnRate | quote }},
          "microblockChiseling": {{ .Values.serverConfig.microblockChiseling | quote }},
          "allowCoordinateHud": {{ .Values.serverConfig.allowCoordinatedHud }},
          "allowMap": {{ .Values.serverConfig.allowMap }},
          "colorAccurateWorldmap": {{ .Values.serverConfig.colorAccurateWorldmap }},
          "loreContent": {{ .Values.serverConfig.loreContent }},
          "clutterObtainable": {{ .Values.serverConfig.clutterObtainable | quote }},
          "temporalStorms": {{ .Values.serverConfig.temporalStorms | quote }},
          "tempstormDurationMul": {{ .Values.serverConfig.temporalstormDurationMul | quote }},
          "temporalStability": {{ .Values.serverConfig.temporalStability }},
          "temporalRifts": {{ .Values.serverConfig.temporalRifts | quote }},
          "temporalGearRespawnUses": {{ .Values.serverConfig.temporalGearRespawnUses | quote }},
          "temporalStormSleeping": {{ .Values.serverConfig.temporalStormSleeping }},
          "worldClimate": {{ .Values.serverConfig.worldClimate | quote }},
          "landcover": {{ .Values.serverConfig.landcover | quote }},
          "oceanscale": {{ .Values.serverConfig.oceanscale | quote }},
          "upheavelCommonness": {{ .Values.serverConfig.upheavelCommonness | quote }},
          "geologicActivity": {{ .Values.serverConfig.geologicActivity | quote }},
          "landformScale": {{ .Values.serverConfig.landformScale | quote }},
          "worldWidth": {{ .Values.serverConfig.mapSizeX | quote }},
          "worldLength": {{ .Values.serverConfig.mapSizeZ | quote }},
          "worldEdge": {{ .Values.serverConfig.worldEdge | quote }},
          "polarEquatorDistance": {{ .Values.serverConfig.polarEquatorDistance | quote }},
          "globalTemperature": {{ .Values.serverConfig.globalTemperature | quote }},
          "globalPrecipitation": {{ .Values.serverConfig.globalPercipitation | quote }},
          "globalForestation": {{ .Values.serverConfig.globalForestation | quote }},
          "surfaceCopperDeposits": {{ .Values.serverConfig.surfaceCopperDeposits | quote }},
          "surfaceTinDeposits": {{ .Values.serverConfig.surfaceTinDeposits | quote }},
          "snowAccum": {{ .Values.serverConfig.snowAccum | quote }},
          "allowLandClaiming": {{ .Values.serverConfig.allowLandClaiming }},
          "classExclusiveRecipes": {{ .Values.serverConfig.classExclusiveRecipes }},
          "auctionHouse": {{ .Values.serverConfig.auctionHouse }},
        },
        "MapSizeY": {{ .Values.serverConfig.mapSizeY | int }},
        "CreatedByPlayerName": null,
        "DisabledMods": null,
        "RepairMode": false
      },
      "NextPlayerGroupUid": 10,
      "GroupChatHistorySize": 20,
      "MaxOwnedGroupChannelsPerUser": 10,
      "OnlyWhitelisted": {{ .Values.serverConfig.onlyWhitelisted }},
      "VerifyPlayerAuth": true,
      "DefaultSpawn": null,
      "AllowPvP": {{ .Values.serverConfig.allowPvP }},
      "AllowFireSpread": {{ .Values.serverConfig.allowFireSpread }},
      "AllowFallingBlocks": {{ .Values.serverConfig.allowFallingBlocks }},
      "HostedMode": false,
      "HostedModeAllowMods": false,
      "StartupCommands": {{ if .Values.serverConfig.startupCommands }}{{ .Values.serverConfig.startupCommands }}{{ else }}null{{ end }},
      "RepairMode": false,
      "AnalyzeMode": false,
      "CorruptionProtection": true,
      "RegenerateCorruptChunks": false,
      "ChatRateLimitMs": 1000,
      "DieBelowDiskSpaceMb": 400,
      "ModIdBlackList": null,
      "ServerIdentifier": null
    }
